### PR TITLE
Adding new Syntax and fixing small issues

### PR DESCRIPTION
**Pull request by AliSawari**
hello @houssem-yahiaoui 
I liked your example for Gridfs file upload in nodejs :+1: 
I've seen some small tiny issues that can cause some problems  :smiley: 
thanks a lot :star:

### CODE REVIEW

**Comment by houssem-yahiaoui** [comment]
Love it ! Cheers Mate !

**Comment by AliSawari** [comment]
Thanks a lot for merging ! 😃 @houssem-yahiaoui 
I'm more than happy to help 
A good UI client for testing the functionality maybe ? 
Whad do you say?

**Comment by houssem-yahiaoui** [comment]
Some minimal like an input with upload button that can generate a link afterward and another page to all uploaded image can be awesome, tell m what you think, you build the UI and i take care of the API :)

**Comment by AliSawari** [comment]
That's great!
I can create a web app with React that allows me to do amazing stuff on the web , you Don't even need another html file! You just create an index.html file and then load all the JavaScript with one element , trust me I know it well , it will be Awesome! 
Can you define me as a contributor please? :) 
I'll set up a simple UI with React tomorrow

**Comment by houssem-yahiaoui** [comment]
That was done, can you please create a new Issue for the UI integration ?

**Pull request merged**
